#!/usr/bin/env python3
"""
Claude Code Review CLI Wrapper

A user-friendly wrapper that handles Docker orchestration, setup verification,
and passes arguments to the containerized review tool.

Usage:
    ./review-cli.py --repo https://github.com/user/repo --reviewer python --use-claude-cli
    ./review-cli.py --help
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path
from typing import List, Optional


class Colors:
    """ANSI color codes for terminal output"""
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
    END = '\033[0m'


def print_header(msg: str):
    """Print a formatted header"""
    print(f"\n{Colors.BOLD}{Colors.BLUE}{'=' * 60}{Colors.END}")
    print(f"{Colors.BOLD}{Colors.BLUE}{msg}{Colors.END}")
    print(f"{Colors.BOLD}{Colors.BLUE}{'=' * 60}{Colors.END}\n")


def print_success(msg: str):
    """Print a success message"""
    print(f"{Colors.GREEN}✓ {msg}{Colors.END}")


def print_error(msg: str):
    """Print an error message"""
    print(f"{Colors.RED}✗ {msg}{Colors.END}", file=sys.stderr)


def get_compose_command() -> Optional[List[str]]:
    """
    Detect available Docker Compose command.

    Returns:
        List of command parts for subprocess, or None if not found.
        - ['docker-compose'] for standalone docker-compose (v1)
        - ['docker', 'compose'] for Docker Compose v2 plugin
    """
    # Try docker-compose (standalone, v1)
    try:
        result = subprocess.run(
            ['docker-compose', '--version'],
            capture_output=True,
            text=True,
            timeout=5
        )
        if result.returncode == 0:
            return ['docker-compose']
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass

    # Try docker compose (plugin, v2)
    try:
        result = subprocess.run(
            ['docker', 'compose', 'version'],
            capture_output=True,
            text=True,
            timeout=5
        )
        if result.returncode == 0:
            return ['docker', 'compose']
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass

    return None


def print_warning(msg: str):
    """Print a warning message"""
    print(f"{Colors.YELLOW}⚠ {msg}{Colors.END}")


def print_info(msg: str):
    """Print an info message"""
    print(f"{Colors.CYAN}→ {msg}{Colors.END}")


def get_script_dir() -> Path:
    """Get the directory where this script is located"""
    return Path(__file__).parent.resolve()


def check_prerequisites() -> bool:
    """Check if all prerequisites are met"""
    print_header("Checking Prerequisites")

    all_good = True

    # Check Docker
    try:
        result = subprocess.run(
            ['docker', '--version'],
            capture_output=True,
            text=True,
            timeout=5
        )
        if result.returncode == 0:
            print_success(f"Docker installed: {result.stdout.strip()}")
        else:
            print_error("Docker not working properly")
            all_good = False
    except (FileNotFoundError, subprocess.TimeoutExpired):
        print_error("Docker not found. Please install Docker first.")
        all_good = False

    # Check docker-compose (v1 standalone) or docker compose (v2 plugin)
    compose_cmd = get_compose_command()
    if compose_cmd:
        # Get version info for display
        version_cmd = compose_cmd + ['version'] if compose_cmd == ['docker', 'compose'] else compose_cmd + ['--version']
        result = subprocess.run(version_cmd, capture_output=True, text=True, timeout=5)
        version_info = result.stdout.strip() if result.returncode == 0 else ' '.join(compose_cmd)
        print_success(f"Docker Compose installed: {version_info}")
    else:
        print_error("Docker Compose not found. Please install docker-compose or docker-compose-v2.")
        all_good = False

    return all_good


def check_oauth_mode(use_oauth: bool) -> bool:
    """Check OAuth prerequisites if using OAuth mode"""
    if not use_oauth:
        return True

    print_header("Checking OAuth Mode Prerequisites")

    all_good = True

    # Check if credentials file exists
    creds_file = Path.home() / '.claude' / '.credentials.json'
    if creds_file.exists():
        print_success(f"Claude credentials found: {creds_file}")
    else:
        print_error(f"Claude credentials not found at {creds_file}")
        print_info("Please run: claude login")
        all_good = False

    return all_good


def setup_environment() -> bool:
    """Set up the environment (.env file, reviews directory)"""
    print_header("Setting Up Environment")

    script_dir = get_script_dir()

    # Create .env file with current user's UID/GID
    env_file = script_dir / '.env'
    uid = os.getuid()
    gid = os.getgid()

    env_content = f"""# Auto-generated by review-cli.py
# This ensures Docker runs as your user to avoid permission issues
USER_ID={uid}
GROUP_ID={gid}
"""

    try:
        with open(env_file, 'w') as f:
            f.write(env_content)
        print_success(f"Created .env with USER_ID={uid} GROUP_ID={gid}")
    except Exception as e:
        print_error(f"Failed to create .env file: {e}")
        return False

    # Create reviews directory if it doesn't exist
    reviews_dir = script_dir / 'reviews'
    try:
        reviews_dir.mkdir(exist_ok=True)

        # Check if writable
        test_file = reviews_dir / '.test'
        test_file.touch()
        test_file.unlink()

        print_success("Reviews directory ready and writable")
    except PermissionError:
        print_error(f"Reviews directory exists but is not writable: {reviews_dir}")
        print_info(f"Fix with: sudo chown -R $(id -u):$(id -g) {reviews_dir}")
        return False
    except Exception as e:
        print_error(f"Failed to set up reviews directory: {e}")
        return False

    return True


def validate_repo_url(repo_url: str) -> bool:
    """Validate repository URL format"""
    if not repo_url:
        print_error("Repository URL is required")
        return False

    # Basic validation - check if it looks like a Git URL
    valid_patterns = [
        'github.com/',
        'gitlab.com/',
        'bitbucket.org/',
        '.git',
        'git@'
    ]

    if not any(pattern in repo_url for pattern in valid_patterns):
        print_warning(f"Repository URL might not be valid: {repo_url}")
        print_info("Expected format: https://github.com/user/repo or git@github.com:user/repo.git")
        response = input("Continue anyway? (y/n): ")
        if response.lower() != 'y':
            return False

    return True


def build_docker_image() -> bool:
    """Build the Docker image if needed"""
    print_header("Preparing Docker Image")

    script_dir = get_script_dir()

    # Check if image exists
    result = subprocess.run(
        ['docker', 'images', '-q', 'claude-reviewer:latest'],
        capture_output=True,
        text=True
    )

    if result.stdout.strip():
        print_success("Docker image already exists: claude-reviewer:latest")
        return True

    print_info("Building Docker image (first time only, may take 2-3 minutes)...")

    # Build the image using detected compose command
    compose_cmd = get_compose_command()
    if not compose_cmd:
        print_error("Docker Compose not found")
        return False

    build_cmd = compose_cmd + ['build']

    try:
        result = subprocess.run(
            build_cmd,
            cwd=script_dir,
            check=False
        )

        if result.returncode == 0:
            print_success("Docker image built successfully")
            return True
        else:
            print_error("Docker build failed")
            return False

    except Exception as e:
        print_error(f"Failed to build Docker image: {e}")
        return False


def run_review(args: argparse.Namespace) -> int:
    """Run the review using docker-compose"""
    print_header("Running Code Review")

    script_dir = get_script_dir()

    # Get compose command (v1 or v2)
    compose_cmd = get_compose_command()
    if not compose_cmd:
        print_error("Docker Compose not found")
        return 1

    # Build docker-compose command
    docker_cmd = compose_cmd + [
        'run',
        '--rm',
        'reviewer',
        '--repo', args.repo,
    ]

    # Add reviewers
    for reviewer in args.reviewer:
        docker_cmd.extend(['--reviewer', reviewer])

    # Add optional arguments
    if args.model:
        docker_cmd.extend(['--model', args.model])

    if args.output_dir:
        docker_cmd.extend(['--output-dir', args.output_dir])

    if args.keep_repo:
        docker_cmd.append('--keep-repo')

    # Handle legacy flags (convert to new format)
    if hasattr(args, 'use_claude_cli') and args.use_claude_cli:
        args.auth = 'oauth'
    if hasattr(args, 'no_agentic') and args.no_agentic:
        args.mode = 'batch'
    if hasattr(args, 'agentic') and args.agentic:
        args.mode = 'agentic'

    # Pass new flags to container
    docker_cmd.extend(['--auth', args.auth])
    docker_cmd.extend(['--mode', args.mode])

    print_info(f"Repository: {args.repo}")
    print_info(f"Reviewers: {', '.join(args.reviewer)}")

    # Auth mode
    if args.auth == 'oauth':
        print_info("Auth: OAuth (using ~/.claude credentials)")
    else:
        print_info("Auth: API Key (using ANTHROPIC_API_KEY)")

    # Review mode
    if args.mode == 'batch':
        print_info("Mode: Batch (sends all files at once - may fail with large repos)")
    else:
        print_info("Mode: Agentic (AI explores repo with tools)")

    print()

    # Run the review
    try:
        result = subprocess.run(
            docker_cmd,
            cwd=script_dir
        )
        return result.returncode
    except KeyboardInterrupt:
        print_warning("\nReview interrupted by user")
        return 130
    except Exception as e:
        print_error(f"Failed to run review: {e}")
        return 1


def main():
    parser = argparse.ArgumentParser(
        description='Claude Code Skills Review Tool - Easy CLI Wrapper',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # OAuth + Batch (default - uses ~/.claude, no API key needed)
  %(prog)s --repo https://github.com/user/repo --reviewer python

  # API Key + Agentic (recommended for large repos - AI explores with tools)
  %(prog)s --repo https://github.com/user/repo --reviewer python --auth apikey --mode agentic

  # OAuth + Batch (explicit)
  %(prog)s --repo https://github.com/user/repo --reviewer python --auth oauth --mode batch

  # API Key + Batch
  %(prog)s --repo https://github.com/user/repo --reviewer python --auth apikey --mode batch

  # Multiple reviewers
  %(prog)s --repo https://github.com/user/repo --reviewer django --reviewer security

  # Specific model
  %(prog)s --repo https://github.com/user/repo --reviewer python --model claude-opus-4-20250514

Available reviewers:
  - agile-requirements-reviewer: Requirements and user stories
  - django-reviewer: Django production readiness
  - python-format-refactoring-reviewer: Python style refactoring
  - javascript-functional-reviewer: JavaScript functional patterns
  - python-functional-reviewer: Python functional patterns
  - python-test-reviewer: Python test quality
  - python-refactoring-reviewer: Python refactoring opportunities
  - python-security-privacy-reviewer: Security and privacy issues
  - python-zen-reviewer: Zen of Python principles

Available tags (expand to multiple reviewers):
  - python: All Python reviewers
  - javascript: All JavaScript reviewers
  - security: Security-focused reviewers
  - django: Django-specific reviewers

For more details, see:
  - SETUP.md: Setup instructions
  - README.md: Full documentation
        """
    )

    parser.add_argument(
        '--repo',
        help='GitHub repository URL to review'
    )

    parser.add_argument(
        '--reviewer',
        action='append',
        help='Reviewer(s) or tag(s) to use (can specify multiple times). '
             'Use --list-reviewers to see all available options.'
    )

    parser.add_argument(
        '--model',
        help='Claude model to use (e.g., claude-sonnet-4-20250514, claude-opus-4-20250514)'
    )

    parser.add_argument(
        '--output-dir',
        default='reviews',
        help='Output directory for review reports (default: reviews)'
    )

    parser.add_argument(
        '--keep-repo',
        action='store_true',
        help='Keep cloned repository after review'
    )

    parser.add_argument(
        '--auth',
        choices=['oauth', 'apikey'],
        default='oauth',
        help='Authentication: "oauth" (uses ~/.claude, default) or "apikey" (uses ANTHROPIC_API_KEY)'
    )

    parser.add_argument(
        '--mode',
        choices=['agentic', 'batch'],
        default='agentic',
        help='Review mode: "agentic" (AI explores with tools, default) or "batch" (sends all files at once)'
    )

    # Legacy flags (hidden)
    parser.add_argument('--use-claude-cli', action='store_true', help=argparse.SUPPRESS)
    parser.add_argument('--no-agentic', action='store_true', help=argparse.SUPPRESS)
    parser.add_argument('--agentic', action='store_true', help=argparse.SUPPRESS)

    parser.add_argument(
        '--skip-checks',
        action='store_true',
        help='Skip prerequisite checks (use with caution)'
    )

    parser.add_argument(
        '--list-reviewers',
        action='store_true',
        help='List all available reviewers and tags, then exit'
    )

    args = parser.parse_args()

    # Handle --list-reviewers flag - run in Docker to access skills
    if args.list_reviewers:
        print_header("Available Reviewers and Tags")

        script_dir = get_script_dir()

        # Get compose command (v1 or v2)
        compose_cmd = get_compose_command()
        if not compose_cmd:
            print_error("Docker Compose not found. Please install docker-compose or docker-compose-v2.")
            sys.exit(1)

        # Run docker-compose with --list-reviewers
        docker_cmd = compose_cmd + [
            'run',
            '--rm',
            'reviewer',
            '--list-reviewers'
        ]

        try:
            result = subprocess.run(docker_cmd, cwd=script_dir)
            sys.exit(result.returncode)
        except subprocess.CalledProcessError as e:
            print_error(f"Failed to list reviewers: {e}")
            sys.exit(1)
        except Exception as e:
            print_error(f"Error running Docker Compose: {e}")
            sys.exit(1)

    # Validate required arguments (only needed when not listing)
    if not args.repo:
        parser.error('--repo is required (use --list-reviewers to see available reviewers)')
    if not args.reviewer:
        parser.error('--reviewer is required (use --list-reviewers to see available reviewers)')

    # Print banner
    print_header("Claude Code Skills Review Tool")

    # Validate repository URL
    if not validate_repo_url(args.repo):
        return 1

    # Check prerequisites
    if not args.skip_checks:
        if not check_prerequisites():
            print_error("Prerequisites check failed")
            return 1

        # Handle legacy flags for prerequisite checks
        use_oauth = (args.auth == 'oauth') or (hasattr(args, 'use_claude_cli') and args.use_claude_cli)

        if not check_oauth_mode(use_oauth):
            print_error("OAuth prerequisites check failed")
            return 1

        if not setup_environment():
            print_error("Environment setup failed")
            return 1

        if not build_docker_image():
            print_error("Docker image preparation failed")
            return 1

    # Run the review
    return run_review(args)


if __name__ == '__main__':
    sys.exit(main())
